### ISSUE TITLE
Some functions not working in new query engine

### ISSUE THREAD

**Issue by davecromberge** [dalmatinerdb/dqe#15]
Functions `derivate` and `confidence` do not appear to work for a time window that is anything less than an hour, which could be due to the chunk mechanism in the new DQE functions.

This works:

```
SELECT confidence(m0) ALIAS 'fd4be66f-03-412e-8ec9-9f230927b629'.'base'.'network'.'eth0'.'packets_sent' 
BUCKET 'fd' AS m0 BETWEEN "2015-11-01 00:00:00" AND "2015-11-01 01:00:00"
```

However, the following query does not return any results:

```
SELECT confidence(m0) ALIAS 'fd4be66f-03-412e-8ec9-9f230927b629'.'base'.'network'.'eth0'.'packets_sent' 
BUCKET 'fd' AS m0 BETWEEN "2015-11-01 00:00:00" AND "2015-11-01 00:59:00"
```

The same applies to `derivate`

**Comment by Licenser** [comment]
fixed :)
