### ISSUE TITLE
Resolution Query KeyWord <<"IN">> is not support in current version of dqe.

### ISSUE THREAD

**Issue by wudixiaotie** [dalmatinerdb/dqe#36]
[dalmatinerdb query-language](https://docs.project-fifo.net/docs/query-language) says that

> By default queries treat incoming data as a one second resolution, however this can be adjusted by passing a resolution section to the query. The syntax is: IN resolution:time.

But I always got an 400 and "Parser error in line 1: syntax error before: <<"IN">>" when I try to get data using KeyWord **<<"IN">>**.

My query is like this:
`SELECT 'adb212ff-b56c-6b01-f262-9d807e'.'cpu'.'usage' BUCKET 'zone'  LAST 30s IN 10`

Then I view the file [dql_lexer](https://github.com/dalmatinerdb/dqe/blob/master/src/dql_lexer.xrl), keyword **IN** does not exist.

Is the doc outdate or there is another keyword for resolution?

**Comment by Licenser** [comment]
Hi yes sorry that is simply outdated. The query engine has since improved quite a bit and now can figure out the resolution itself.

**Comment by Licenser** [comment]
replaced the docs with a link to the current (up to date) documentaiton.

**Comment by wudixiaotie** [comment]
@Licenser Thanks, but the situation is, the chrome crashed when I try to query <<"LAST 2d">>. The response contains 4900 values, more than I need. I expect less than 200 values in one response. How could I do that?

**Comment by wudixiaotie** [comment]
Oh, I should try query like this:
`SELECT avg('057345b6-76b1-4a40-aac9-139818ca3a58'.'cpu'.'usage' BUCKET 'zone', 1d)  LAST 2d`

There only 2 values in the response.
Problem solved.
👍 
:)
